### Get all vehicles
GET http://localhost:8080/api/vehicles/


### Get all vehicle types
GET http://localhost:8080/api/types/


### Create new vehicle type
POST http://localhost:8080/api/types/
Content-Type: application/json

{
  "name": "motorcycle",
  "yearOfInvention": 1885
}


### Create new vehicle
POST http://localhost:8080/api/types/f78f5c1c-fa3d-4cdf-a9fc-11325ac0747e/vehicles/
Content-Type: application/json

{
  "brand": "Suzuki",
  "yearOfProduction": 2020
}


### Update vehicle
PUT http://localhost:8080/api/vehicles/8a30237c-6b53-41d1-bdff-93fca3040804/
Content-Type: application/json

{
  "brand": "Yamaha turbo",
  "yearOfProduction": 2020
}


### Delete vehicle (BMW)
DELETE http://localhost:8080/api/vehicles/bcb48ddd-ff8c-34b5-b452-ee573b4db770/

### Get all vehicles
GET http://localhost:8080/api/vehicles/


### Get a vehicle type
GET http://localhost:8080/api/types/6a09b5a8-a986-42a6-86dc-ba04615650a2/


### Get vehicle types
GET http://localhost:8080/api/types/


### Update a vehicle type
PUT http://localhost:8080/api/types/6a09b5a8-a986-42a6-86dc-ba04615650a2/
Content-Type: application/json

{
  "name": "Not car",
  "yearOfInvention": 1000
}


### Delete a vehicle type
DELETE http://localhost:8080/api/types/f78f5c1c-fa3d-4cdf-a9fc-11325ac0747e/